### ISSUE TITLE
#HW2 frequency words

### ISSUE THREAD

**Issue by AlFilippov** [DumDereDum/Andro#4]
Привет ::
По заданию HW2 на hashmap 
**Небольшие замечания :**
1. Даже такие небольшие операции - можно разбивать на методы либо на классы ( если будет требоваться дальнейшее использование этих фич ) , чтобы все в Main не было кучей . 
К примеру : Ввод оставляем в main ,а  разделение и итерацию по массиву в отдельный метод . У которого можно будет сделать return type HashMap<String,Integer> 
2.По поводу стандартной реализации цикла for ,  посмотри по условиям , которые тебе нужно выполнить  это - переменную типа String поискать в массиве . Для этого отлично подходит цикл for-each . 
Поправь , пожалуйста относительно замечаний и коммитни - там отпиши мне(телега @friendstiv) либо Екатерине

**Comment by DumDereDum** [comment]
Данное задание было исправлено.
